### ISSUE TITLE
File not found in your Nofile.io link 

### ISSUE THREAD

**Issue by sigit-purnomo** [cahya-wirawan/language-modeling#2]
Dear Pak Cahya,

I have tried your script with my dataset. I got a problem because I don't have the _wiki_id_lm.h5_ file. I think the file is located on your Nofile.io link in readme files but when I clicked it, it shows a message: a file not found. Could you help me to fix it?

Thank you
Sigit Purnomo

**Comment by cahya-wirawan** [comment]
Hi,
It seems the file was removed on the server, maybe I forget to set it to be available for ever. Thanks for the notification. I will upload it again later, and let you know.
Cahya.

**Comment by sigit-purnomo** [comment]
Thank you...

**Comment by cahya-wirawan** [comment]
Hi,
I have updated the link to the pre-trained model version 0.1, and added a new one for version 0.2.
You can test the model using the script ulmfit_test.py (please do "git pull" before using it and change the LM_PATH accordingly). It will generate a sentence based on your input. The script is still messy now, but for testing purpose it should work. Just let me know if you have any questions or other issues.

**Comment by sigit-purnomo** [comment]
Thank you Pak Cahya
