### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by wahyubram82** [cahya-wirawan/language-modeling#3]
bg cahya, boleh minta file 'wiki_id_lm.h5' dan file 'wiki_id_itos.pkl'-nya? saya sedang coba membuat speech recognition, tapi sulit sekali mendapatkan data set untuk dibuat lm-nya...apalagi untuk train.

tahap pertama speech recognition, membuat lm, karena saya menggunakan deepspeech jadi saya akan membuatnya dengan kenlm / memformat yg sudah ada ke format kenlm, sekalian mohon petunjuk untuk konversi ke format kenlm.

terima kasih ya mas, kemajuan teknologi di bidang bahasa Indonesia sangat lambat, mayoritas karena yg tertarik belajar, cenderung memulai dari awal...pasti perkembangan tekonologi kita akan lebih mantap kalau banyak bahan setengah jadi seperti yang mas buat.

**Comment by cahya-wirawan** [comment]
Hallo, file 'wiki_id_lm.h5' dan file 'wiki_id_itos.pkl' ada di https://drive.google.com/open?id=1NzWqxRau8SHBvmvgqnlNlNYVjJcQYSJc (sebenernya link nya dah ada di repo, dibawah).

mengenai konversi dr neural network lm ke kenlm, saya sendiri jg sedang mencari gimana caranya. 
Kalau di Kaldi ada RNNLM rescoring pakai rnnlm lattice rescoring: https://github.com/kaldi-asr/kaldi/blob/master/scripts/rnnlm/lmrescore_pruned.sh
algorithma nya ada di https://www.danielpovey.com/files/2018_icassp_lattice_pruning.pdf, 
saya sendiri belum coba sih. kasih tahu ya kalau dah coba

**Comment by wahyubram82** [comment]
Siap mas nanti klu berhasil saya share hasilnya. Terima kasih banyak sebelumnya...

**Comment by wahyubram82** [comment]
mas cahya, panduan untuk membuat language model dalam rangka speech recognition ada dalam petunjuk di link ini:
https://tilmankamp.github.io/FOSDEM2018/

pada tahapan download text sebelum perintah: 
lmplz -o 5 <some-text.txt>lm.arpa

text yang jadi acuan harus di download dulu, artinya, salah satu dokumen file pada salah satu proses / fase yang dilakukan mas cahya dalam membuat language model ini, diperlukan untuk membuat model ken-lm.

jadi yang saya lakukan, saya mengambil semua dokumen yang mas cahya gunakan untuk dijadikan acuan pembuatan language model di ken-lm.

mengingat prinsip speech recognition pada dasarnya adalah prediksi / kalkulasi kemungkinan kata berdasarkan perhitungan padanan huruf vokal dari sebuah kata yang sering digunakan, bukan memprediksi setiap konsonan dari seluruh kata yang ada di kamus. maka sebanyak-banyaknya artikel dan tulisan membuat komputer menjadi lebih 'terbantu' dalam memprediksi.

setelah itu, kata di artikel harus digabung semua menjadi satu buah text besar dan kita harus membuat model speech recognition. saat wer yang diinginkan sudah tercapai, model bisa di share untuk dikembangkan dalam rangka menambahkan 'kemampuan' prediksi kata.

model yang mas cahya buat, nantinya bisa digunakan untuk melakukan 'live' train, klu sudah ada model speech yang bagus, bisa dipakai untuk membuat text to voice, dimana wav yang terbentuk diinput untuk bahan train. nah text to voice ini baca textnya dari text punya mas cahya...

jadi ke depan klu mau train tidak perlu banyak dataset.

**Comment by wahyubram82** [comment]
mas cahya, saya kesulitan untuk membuka wikipedia xml...

namun saya perhatikan, ken lm pada dasarnya mengacu kepada lm.arpa, yang isinya gram dari setiap kata, contoh format:

\data\
ngram 1=18070
ngram 2=156582
ngram 3=281336
ngram 4=328440
ngram 5=344596

\1-grams:
-2.740511	sampai	-0.49692822
-4.532232	kelahiran	-0.11159151
-2.5845103	adalah	-0.28963566
-2.5974884	seperti	-0.32350793
-4.260376	berikut	-0.13528475
-5.062365	cokelat	-0.11159151
-5.062365	bantalku	-0.11159151
-5.062365	disampingnya	-0.11159151
-5.062365	pemburu	-0.11159151
-5.062365	menembak	-0.11159151
-5.062365	antik	-0.11159151
-5.062365	permen	-0.11159151
-5.062365	bawakan	-0.11159151
-5.062365	bhinneka	-0.11159151
-5.062365	ika	-0.11159151
-3.316235	ibu	-0.38254136
-2.6847367	nya	-0.47805452

\2-grams:
-3.3278487	mereka inilah	-0.04883205
-3.541432	karena inilah	-0.04883205
-3.5602694	tetapi inilah	-0.04883205
-2.2655876	maksud inilah	-0.04883205

\3-grams:
-0.9633899	dimensi terakhir inilah	-0.021315977
-2.205309	di sektor inilah	-0.021315977
-0.97314894	dongeng dan silsilah	-0.021315977

dst..

apakah ada file-nya mas cahya, klu ada boleh di share
